[package]
name = "kaitai"
version = "0.11.0"
authors = ["Bradlee Speice <bradlee@speice.io>", "Aon"]
edition = "2018"

[dependencies]
encoding-next = "0.3"
cp437 = "*"
unicode-segmentation = "1.9.0"
flate2 = "1.0"

[dev-dependencies]
tempfile = "3.4.0"
